### ISSUE TITLE
getting TlsException (HandshakeFailed (Error_Protocol ("certificate has unknown CA",True,UnknownCa)))

### ISSUE THREAD

**Issue by ababkin** [snoyberg/haskell-scratch#5]
Hi

Trying out the haskell-scratch for my project that uses aws package to upload files to S3.
I've extended the set of shared libs with libssl and libcrypto as it needed them.

Now I'm getting this error message with a trivial S3 uploader:

```
TlsException (HandshakeFailed (Error_Protocol ("certificate has unknown CA",True,UnknownCa)))
```

Any ideas ? I suspect this is caused by the minimal haskell-scratch setup but I don't know much about setting up certificates.

Thank you

**Comment by snoyberg** [comment]
I'm sure that's the cause, but I don't have advice on how to solve it.
strace inside a chroot may help.

**Comment by ababkin** [comment]
ok, found a workaround (basically disabling certificate). 
http://blog.matthewja.com/post/108812034379/haskell-anu-qrng

**Comment by purefn** [comment]
Can we reopen this issue? I'm running into the same thing and would rather not disable certificate verification to make it work. It looks like the image is missing the `/etc/ssl/certs` directory. If we add that, it should start working correctly.

**Comment by snoyberg** [comment]
Please see discussion on #4, same logic applies
