### ISSUE TITLE
What does this line mean in the example? 

### ISSUE THREAD

**Issue by langston-barrett** [snoyberg/haskell-scratch#6]
``` Dockerfile
haskell-scratch:integer-gmp
```

Why is there a suffix of `:integer-gmp`? Could this perhaps be explained by a comment in the example Dockerfile?

**Comment by snoyberg** [comment]
Looks like @dysinger added this in https://github.com/snoyberg/haskell-scratch/commit/08e381de3acbe3213227d614467a4c75d3c9d693.

**Comment by langston-barrett** [comment]
It certainly looks like it has to do with the integer arithmetic backend. Perhaps a list of supported tags/backends could be provided in the README? 

A link to [this post](https://www.fpcomplete.com/blog/2015/05/haskell-web-server-in-5mb) might also be helpful for those that stumble upon this repo.
