### ISSUE TITLE
Not working on Archlinux

### ISSUE THREAD

**Issue by jpotier** [snoyberg/haskell-scratch#8]
Of course it doesn't. Path is different in Archlinux.
I made several change to make my haskell project work, but I don't really know how to contribute back to this project, since it requires to rewrite a big part of the `Makefile`.
For now I'll just fork and upload the alternate version.

**Comment by jpotier** [comment]
It is available here: https://github.com/jpotier/haskell-scratch

**Comment by snoyberg** [comment]
I'd recommend sending a PR to the README with a pointer to your repo and explaining its purpose for Archlinux. A comment stating that this repo is Debian/Ubuntu-specific would be great as well.
